version: "3.7"
services:
  proyecto-mini:   
    container_name: proyecto-mini  
    image: proyecto-mini:v1 
    build:
      context: .
    ports:
      - "4002"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT= 4002
    networks:
      - proyectoweb-app

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - proyectoweb-app
networks:
  proyectoweb-app:
  